### ISSUE TITLE
Upgrading from 1.3.4 to 1.3.6 breaks existing cryptfile keyring

### ISSUE THREAD

**Issue by fruboes** [frispete/keyrings.cryptfile#15]
It seems, that upgrading keyrings.cryptfile from 1.3.4 to 1.3.6 breaks existing cryptfile-based keyrings, resulting in "MAC check failed" error message on reading.

Steps to reproduce are following:
```
python3.6 -m venv venv
source venv/bin/activate
pip install wheel
pip install keyrings.cryptfile==1.3.4
export XDG_DATA_HOME=`pwd`
# Please find set.py and get.py files attached below (get_set.tar.gz file)
./set.py # creates new keyring with a single service password
./get.py # correctly prints password retrieved from keyring (cryptfile)

pip install keyrings.cryptfile==1.3.6

./get.py
(...)
File "/home/tfruboes/work_2020_2/2020.10.cryptFileBug/venv/lib/python3.6/site-packages/Crypto/Cipher/_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed
```
Files needed to reproduce are inside this tarball: [get_set.tar.gz](https://github.com/frispete/keyrings.cryptfile/files/5317901/get_set.tar.gz) .

Could you have a look on this?

**Comment by mariano54** [comment]
I am seeing the same issue, upgraded to 1.3.6 and Have the Mac check failed.

Traceback (most recent call last):
  File "/home/mariano54/Chia/chia-blockchain/venv/lib/python3.8/site-packages/keyrings/cryptfile/file_base.py", line 106, in get_password
    password = self.decrypt(password_encrypted, assoc).decode('utf-8')
  File "/home/mariano54/Chia/chia-blockchain/venv/lib/python3.8/site-packages/keyrings/cryptfile/cryptfile.py", line 130, in decrypt
    return cipher.decrypt_and_verify(data['data'], data['mac'])
  File "/home/mariano54/Chia/chia-blockchain/venv/lib/python3.8/site-packages/Crypto/Cipher/_mode_gcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/home/mariano54/Chia/chia-blockchain/venv/lib/python3.8/site-packages/Crypto/Cipher/_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed

**Comment by frispete** [comment]
Would you guys check the keyring_key branch, please?

It's not perfect - still failing one test, and specific tests to test this issue are still missing. 

I would like to discuss this with @jaraco since it's almost his territory...

**Comment by fruboes** [comment]
Apologies for late follow-up. I did the following
```
git clone https://github.com/frispete/keyrings.cryptfile.git
cd keyrings.cryptfile/
git checkout keyring_key
git log 
> commit 5a846c583ae756663fcad4ed382b258a00e809bc (HEAD -> keyring_key, origin/keyring_key)
> Author: Hans-Peter Jansen <hp@urpla.net>
> Date:   Wed Oct 7 21:55:43 2020 +0200
>   file.py: attempt to fix explicit keyring_key handling
> (...)
pip install -e .
```
Unfortunately problem is still present, i.e. I get 'ValueError: MAC check failed' on read.

**Comment by hoffmang9** [comment]
Still a problem in 1.3.8

I tested with cryptography==3.4.1 and keyring==22.3.0

**Comment by hoffmang9** [comment]
```
File "/home/hoffmang/chia-blockchain/venv/lib/python3.8/site-packages/Crypto/Cipher/_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed
```

**Comment by frispete** [comment]
Did you tried to create a new keyfile, or reused one, that was created with an earlier release?

If you redo the steps from the [README.md](https://github.com/frispete/keyrings.cryptfile/blob/master/README.md), possibly after saving `~/.local/share/python_keyring/cryptfile_pass.cfg` away, mind showing the step, where it broke?

The resulting keyfile should look similar to:
```
[keyring_2Dsetting]
password_20reference = 
        eyJzYWx0IjogIkVvSld0bHRHOCtubnZCYTFGeWZBaWc9PSIsICJkYXRhIjogInhmNGFpWk80YVhj
        S3p6MWsySGVoZ0dWV0NMWVRHMlhVIiwgIm1hYyI6ICJWS0ZDTTlhR0JURk5pTFZIaDB4Y3RRPT0i
        LCAibm9uY2UiOiAidG9nRW5qaWZJUlNjTTh3NmZCSjJLUT09In0=
scheme = [Argon2] AES128.GCM
version = 1.3.8

[service]
user = 
        eyJzYWx0IjogIk4xMHlVdFVaeDVGSkh0OTlrbkVZMXc9PSIsICJkYXRhIjogIm9KVWlXNjR0Iiwg
        Im1hYyI6ICJndGRLUUJVcGZxa3duSG5LVHJNUlh3PT0iLCAibm9uY2UiOiAicGRTeXBGcHkrVDg5
        L3cxamZHTzJLQT09In0=

```

**Comment by frispete** [comment]
Well, I'm a bit behind:
```
python38-argon2-cffi-20.1.0-1.3.x86_64
python38-keyring-21.2.1-105.1.noarch
python38-keyrings.alt-4.0.2-1.2.noarch
python38-keyrings.cryptfile-1.3.8-2.1.noarch
python38-pycryptodome-3.9.9-1.2.x86_64
```

**Comment by frispete** [comment]
> Still a problem in 1.3.8
> 
> I tested with cryptography==3.4.1 and keyring==22.3.0

We do not have any business with cryptography, btw.

**Comment by nbily1** [comment]
I have the same issue after upgrading from 1.3.4 to 1.3.8.

If I downgrade back to 1.3.4, everything seems to work fine again.

On 1.3.8, if I revert the changes in this diff, it successfully unlocks my keyring without the MAC error.

https://github.com/frispete/keyrings.cryptfile/commit/5a846c583ae756663fcad4ed382b258a00e809bc#diff-3a47207a10886c699f5d1eb865e71298937795278fa651a0157be58e185812e8L87

However, I still get the error when I try to retrieve a password that was created in the older version.

Also, after reverting that file, I can use `set_password()` and it creates a new entry that I can retrieve with no issue.

**Comment by frispete** [comment]
Hi @nbily1, the pity here is, nobody attempted to do, what I asked for. Could **you** do me a flavor and redo the steps from the readme with 1.3.4 and do the same with 1.3.8, and check, at what step it broke, with the resulting keyfiles, please?

That would be awesome.

**Comment by frispete** [comment]
Thanks, that was helpful. Will look into it at the weekend (hopefully), quite a lot going on these days...

**Comment by altendky** [comment]
In #19 I have proposed returning to the `'\0'` form for 1.3.9+.  If anyone has opinions about that, or other points, let me know.

**Comment by frispete** [comment]
Oh, wow, good catch, Kyle! I am happy to support the request that goes back to the original '\0'. 

I don't know what got into me at the time. Obviously, testing didn't cover this, therefore, I happy to merge your changes.

**Comment by altendky** [comment]
Hum...  so I went and tested at our application level and apparently we are creating files that don't contain the version info unlike the example files I created using this fish (not bash) loop.  I guess I'll have to research some more to figure out how this is triggered and how it can reasonably be addressed.  It has been suggested that for reading we could just try both options...  `:|`

```bash
for v in 1.3.4 1.3.5 1.3.6 1.3.7 1.3.8; rm -rf venv; python3.10 -m venv venv; venv/bin/pip install git+https://github.com/frispete/keyrings.cryptfile@v$v; venv/bin/python -c 'from keyrings.cryptfile.cryptfile import CryptFileKeyring; kr = CryptFileKeyring(); kr.set_password("service", "user", "secret")'; mv ~/.local/share/python_keyring/cryptfile_pass.cfg cp$v.cfg; end
```

**Comment by altendky** [comment]
I have since tested again and it has worked and I am unsure what made my first test succeed.  So, there may be more corners to clean up around this but I think I would be able to use a 1.3.9 release at this point.

Does anyone else have some time to test out the fix?  It's on `master` at this point.

**Comment by altendky** [comment]
We've got our changes lined up around a 1.3.9 release.  @frispete, do you have time available coming up for a release?

**Comment by frispete** [comment]
Thanks for your engagement, Kyle. 

Will do a release tomorrow!

**Comment by frispete** [comment]
New release published and `master` branch renamed to `main`.

**Comment by frispete** [comment]
Now, that this issue is addressed, let's close it! 

Thanks again, Kyle! Would you be interested in co-maintainership?

**Comment by altendky** [comment]
> Would you be interested in co-maintainership?

I don't expect to be doing a lot of work here, but if you want to add my accounts to provide some redundancy of maintainers, that's fine by me.  If you do, maybe send me an email (listed on my GitHub profile) as well for any private procedural discussions.

http://github.com/altendky
https://pypi.org/user/altendky/
