### ISSUE TITLE
Not on PyPi?

### ISSUE THREAD

**Issue by wade-tattersall** [frispete/keyrings.cryptfile#3]
Hi,

Thanks for this package, it's really useful for what I'm doing at the moment. I'm currently mystified at how people distribute passwords to their microservices without something like this.

https://pypi.org/project/keyring/ mentions keyrings.cryptfile as an alternative backend, but it's not actually on PyPi as near as I can tell - the link to it 404's. 

Is there a reason for this? It'd make dependency management a little easier. I can try to do it for you if you like, though I've no experience in such things.

And as an aside, it might be worth mentioning in the documentation that you can use
```
kr.keyring_key = "your keyring password"
```
to prevent it from querying using `getpass()` (eg: pulling it from an environment variable). It's a good feature, and I was glad when I found it, but it wasn't obvious to me.

Regards,

Wade

**Comment by frispete** [comment]
Thanks for noticing. 

Fixed now: https://pypi.org/project/keyrings.cryptfile/

It took a little in order to get the markdown displayed correctly on PyPI,

For the kr.keyring_key issue: the keyring project definitely welcomes PRs ;-)..

Let me know, if you discover any other issues.
