### ISSUE TITLE
Cannot cleanly install from setup.py

### ISSUE THREAD

**Issue by ecederstrand** [frispete/keyrings.cryptfile#5]
setup.py mentions `keyring` as a dependency, but also contains `from keyrings.cryptfile.cryptfile import __version__ as version` which only works if `keyring` is already installed. So `keyrings.cryptfile` cannot be installed in a clean environment.

The solution is to place `__version__` in a file that does not contain external imports.

**Comment by frispete** [comment]
Finally released 1.3.2 on PyPI with your fix included...

Thanks again,
Pete
