### ISSUE TITLE
Cannot set password via Environment Variable

### ISSUE THREAD

**Issue by samrees** [frispete/keyrings.cryptfile#9]
For use as a library, it would be delightful if the keyring looked for a KEYRING_CRYPTFILE_PASSWORD or similar before calling out to getpass().

**Comment by toyg** [comment]
This can already be achieved by using the keyring explicitly.
```python
from os import getenv
from keyrings.cryptfile.cryptfile import CryptFileKeyring
kr = CryptFileKeyring()
kr.keyring_key = getenv("KEYRING_CRYPTFILE_PASSWORD") or getpass.getpass()
keyring.set_keyring(kr)
```

**Comment by frispete** [comment]
Thanks again @toyg 

I would love to accept a submission from your comments to a Notes section in the README.md. :wink:

Please note, that the environment exists for the whole run time of the process, is accessible through /proc/PID/environ for all processes with enough permission (process group), and is preserved in the hibernation stack as well...

**Comment by pawamoy** [comment]
So, could this be done like this?

```python
import keyring

keyring.get_keyring().keyring_key = "my_keyring_password"
```

**Comment by genotrance** [comment]
Would be ideal if the `KEYRING_CRYPTFILE_PASSWORD` environment variable was already supported by this library. That way, every app will not need to add this code to enable it. This is how [sagecipher](https://pypi.org/project/sagecipher/) does it with `KEYRING_PROPERTY_SSH_KEY_FINGERPRINT`.

I would like the users of [Px](https://github.com/genotrance/px/issues/188) to be able to use `keyrings.cryptfile` without having to add explicit support in Px itself. They can just install this package, set the environment variable and Px will simply work. Instead, it will prompt for a password which does not work for an app like Px which is expected to run in the background.

Update: looks like this was just [added](https://github.com/frispete/keyrings.cryptfile/pull/30). I was looking at PyPi so didn't notice the README changes. Look forward to the new version release - thanks!
